import { describe, it, expect } from 'vitest';
import { optimizeSvg } from '../svg.js';

// ID referenced internally via url(#...) — svgo will keep it but may rename it
const SAMPLE_SVG = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by design tool -->
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100">
  <defs>
    <linearGradient id="myGradient" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:#ff0;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#f00;stop-opacity:1" />
    </linearGradient>
  </defs>
  <rect   width="100"   height="100"   fill="url(#myGradient)" />
  <circle cx="50" cy="50" r="40" stroke="blue"   stroke-width="2"   fill="none" />
</svg>`;

const inputBuffer = Buffer.from(SAMPLE_SVG, 'utf-8');

describe('optimizeSvg', () => {
  describe('optimization', () => {
    it('reduces output size', () => {
      const result = optimizeSvg(inputBuffer);
      expect(result.outputSize).toBeLessThan(result.originalSize);
    });

    it('removes comments', () => {
      const result = optimizeSvg(inputBuffer);
      expect(result.buffer.toString('utf-8')).not.toContain('<!--');
    });

    it('removes unnecessary whitespace', () => {
      const result = optimizeSvg(inputBuffer);
      const output = result.buffer.toString('utf-8');
      expect(output).not.toMatch(/\s{2,}/);
    });

    it('output is valid SVG', () => {
      const result = optimizeSvg(inputBuffer);
      const output = result.buffer.toString('utf-8');
      expect(output).toContain('<svg');
      expect(output).toContain('</svg>');
    });
  });

  describe('ID handling', () => {
    it('preserves readable IDs by default (minifyIds: false)', () => {
      const result = optimizeSvg(inputBuffer);
      expect(result.buffer.toString('utf-8')).toContain('myGradient');
    });

    it('renames IDs when minifyIds: true', () => {
      const result = optimizeSvg(inputBuffer, { minifyIds: true });
      expect(result.buffer.toString('utf-8')).not.toContain('myGradient');
    });

    it('minified IDs produce smaller output', () => {
      const withIds = optimizeSvg(inputBuffer, { minifyIds: false });
      const withoutIds = optimizeSvg(inputBuffer, { minifyIds: true });
      expect(withoutIds.outputSize).toBeLessThanOrEqual(withIds.outputSize);
    });
  });

  describe('size tracking', () => {
    it('reports correct originalSize', () => {
      const result = optimizeSvg(inputBuffer);
      expect(result.originalSize).toBe(inputBuffer.length);
    });

    it('reports correct outputSize', () => {
      const result = optimizeSvg(inputBuffer);
      expect(result.outputSize).toBe(result.buffer.length);
    });
  });

  describe('output validity', () => {
    it('works with no options (all defaults)', () => {
      expect(() => optimizeSvg(inputBuffer)).not.toThrow();
    });
  });
});
